### ISSUE TITLE
希望加入法律新舊版本對比

### ISSUE THREAD

**Issue by shouya** [DannyVim/Chinese_Laws#3]
譬如憲法，可以通過先提交舊版，再根據每次修正案提交新版並覆蓋舊版，如此乃至最新版本。這樣可以方便通過 diff 功能查看不同憲法版本之間的修改內容。

**Comment by DannyVim** [comment]
嗯嗯。确实呢。我会按照你说的来更新的。不过我最近忙于学业，一时间没能更新呢。我打算重新修改一下列表，原来的法条列表还是有一些问题。不少的都是人们平时不会接触到的呢
