### ISSUE TITLE
怎么只剩下宪法了？

### ISSUE THREAD

**Issue by hyh19962008** [DannyVim/Chinese_Laws#6]
其他之前整理的法律去哪了？

**Comment by DannyVim** [comment]
对不起这位老兄了，因为后来有别的事情，然后又发现法律条文太多了，更新太频繁哎。也许现实生活的事务减少了一些之后，会不玩这个项目。真是抱歉。

**Comment by crapthings** [comment]
各种条例啥的也挺重要的，内容非常多。

**Comment by DannyVim** [comment]
欢迎PR

**Comment by g8up** [comment]
兄弟们，这里还有个 repo 值得关注：https://github.com/chuan6/structured-law-document
